if [[ $platform == 'linux' ]]; then
	alias ls='ls -F --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
	alias senz='sensors'
elif [[ $platform == 'darwin' ]]; then
	alias ls='ls -CF'
	alias subl='sublime'	# sublime-text-2 as in Linux command subl
fi

alias cbag='cat ~/.bash_aliases | grep '

# linux, put in /etc/bash.bashrc
alias clr='clear'
alias ..='cd ..'
alias ...='cd ../../'
alias ..3='cd ../../../'

alias ll='ls -al'
alias la='ls -a'
alias l='ls'
# /etc/bash.bashrc

# !=== Script ===
alias rby='ruby'
alias cfe='coffee'
alias py='python'
alias reg='regetron'

# !=== GIT ===
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gcmm='git commit -m'
alias gca='git commit -a'
alias gph='git push'
alias gpl='git pull'
alias gb='git branch'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcp='git checkout production'
alias gfg='git fetch github'
alias gfb='git fetch bucket'

# !=== GEMS ===
alias ccb='cucumber'
alias rsp='rspec'
alias shotgun47='shotgun --port=4567'

# !=== ZEUS ===
alias zzs='zeus start'
alias ztr='zeus test'
alias ztc='zeus cucumber'
alias zs='zeus server'
alias zc='zeus console'
alias zcb='zeus console --sandbox'
alias zr='zeus rake'
alias zd='zeus destroy'
alias zg='zeus generate'

# !=== RAILS ===
alias rn='rails new'
alias rcb='rails console --sandbox'
alias rc='rails console'
alias rg='rails generate'
alias rd='rails destroy'

alias rs='rails server'
alias rs31='rails server --port=3001'
alias rs32='rails server --port=3002'
alias rs33='rails server --port=3003'
alias rs34='rails server --port=3004'
alias rs35='rails server --port=3005'

alias bx='bundle exec'
alias bxan='bundle exec annotate'
alias bxr='bundle exec rspec'
alias bxc='bundle exec cucumber'

# !=== RAKE ===
alias rdl='rake db:schema:load'
alias rds='rake db:seed'
alias rdr='rake db:reset'
alias rddrop='rake db:drop'

alias bxdl='bundle exec rake db:schema:load; bundle exec rake db:schema:load RAILS_ENV=test'
alias bxdm='bundle exec rake db:migrate; bundle exec rake db:migrate RAILS_ENV=test'
alias bxdre='bundle exec rake db:migrate:redo; bundle exec rake db:migrate:redo RAILS_ENV=test'
alias bxddr='bundle exec rake db:drop; bundle exec rake db:drop RAILS_ENV=test'
alias bxdrb='bundle exec rake db:rollback'
alias bxdpp='bundle exec rake db:populate; bundle exec rake db:test:prepare'

# !=== GRUNT ===
alias grtw='grunt watch'

# !=== HEROKU ===
alias herelic='heroku addons:open newrelic'
alias helog='heroku logs'
alias helgrep='heroku logs | grep '

# jumping - repos
alias repos='cd ~/Repos'
alias enspiral='cd ~/Repos/enspiral'
alias work='cd ~/Repos/work'
alias nix-settings='cd ~/Repos/NIX_settings'

# --- current projects
alias insighter='cd ~/Repos/enspiral/insighter'