if [[ $platform == 'linux' ]]; then
	alias ls='ls -F --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias senz='sensors'

	alias myxstart='sudo service mysql start'
	alias mystop='sudo service mysql stop'
	alias myrestart='sudo service mysql restart'

	# !=== Ubuntu specific ===
	alias aptup='sudo apt-get update'
	alias aptug='sudo apt-get upgrade'
	alias aptuu='sudo apt-get update && sudo apt-get upgrade'
	alias aptrepo='sudo add-apt-repository '
	alias aptcs='apt-cache search '

elif [[ $platform == 'darwin' ]]; then
	alias ls='ls -CF'
	alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
	alias subl2='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
	alias updatedb='sudo /usr/libexec/locate.updatedb'

	alias lload='launchctl load'
	alias lunload='launchctl unload'
	alias sulload='sudo launchctl load'
	alias sulunload='sudo launchctl unload'

	alias myload='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
	alias myunload='launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
	alias nginxload='sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist'
	alias nginxunload='sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist'
fi

alias cbag='cat ~/.bash_aliases | grep '
alias bashrefresh='. ~/.bash_profile'

# linux, put in /etc/bash.bashrc
alias clr='clear'
alias ..='cd ..'
alias ...='cd ../../'
alias ..3='cd ../../../'

alias la='ls -a'
alias ll='ls -al'
alias l='ls'
# /etc/bash.bashrc

# !=== Script ===
alias rby='ruby'
alias cfe='coffee'
alias py='python'

# !=== GIT ===
alias gd='git diff'
alias gl='git log'
alias gl1='git log --oneline'
alias gf='git fetch'
alias gst='git status'
alias ga='git add --ignore-removal'
alias gaa='git add --all'
alias grh='git reset HEAD'
alias gc='git commit'
alias gcmm='git commit -m'
alias gca='git commit -a'
alias gph='git push'
alias gpl='git pull'
alias gb='git branch'
alias gbr='git branch --remote'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcp='git checkout production'

# !=== GEMS ===
alias ccb='cucumber'
alias rsp='rspec'
alias shotgun47='shotgun --port=4567'

# !=== ZEUS ===
alias zzs='zeus start'
alias ztr='zeus test'
alias ztc='zeus cucumber'
alias zc='zeus console'
alias zcb='zeus console --sandbox'
alias zr='zeus rake'
alias zd='zeus destroy'
alias zg='zeus generate'
alias zs='zeus server'
alias zs31='zeus server --port=3001'
alias zs32='zeus server --port=3002'
alias zs33='zeus server --port=3003'
alias zs34='zeus server --port=3004'
alias zs35='zeus server --port=3005'

alias zrt='zeus rake_test'
alias zrdm='zeus rake db:migrate; zeus rake_test db:migrate'
alias zrdrb='zeus rake db:rollback; zeus rake_test db:rollback'
alias zeset-testdb='zeus rake_test db:drop; zeus rake_test db:create; zeus rake_test db:schema:load'

# !=== RAILS ===
alias rn='rails new'
alias rcb='rails console --sandbox'
alias rc='rails console'
alias rg='rails generate'
alias rd='rails destroy'

alias rs='rails server'
alias rs31='rails server --port=3001'
alias rs32='rails server --port=3002'
alias rs33='rails server --port=3003'
alias rs34='rails server --port=3004'
alias rs35='rails server --port=3005'

alias r2s='script/server'
alias r2c='script/console'

alias bx='bundle exec'
alias bxan='bundle exec annotate'
alias bxr='bundle exec rspec'
alias bxc='bundle exec cucumber'

# !=== RAKE ===
alias reset-testdb='bundle exec rake db:drop RAILS_ENV=test; bundle exec rake db:create RAILS_ENV=test; bundle exec rake db:schema:load RAILS_ENV=test'
alias rrt='rake routes'
alias rrgrep='rake routes | grep '
alias rdstt='rake db:migrate:status'

alias bxdl='bundle exec rake db:schema:load; bundle exec rake db:schema:load RAILS_ENV=test'
alias bxdm='bundle exec rake db:migrate; bundle exec rake db:migrate RAILS_ENV=test'
alias bxdre='bundle exec rake db:migrate:redo; bundle exec rake db:migrate:redo RAILS_ENV=test'
alias bxddr='bundle exec rake db:drop; bundle exec rake db:drop RAILS_ENV=test'
alias bxdrb='bundle exec rake db:rollback'

# !=== GRUNT ===
alias grtw='grunt watch'

# !=== HEROKU ===
alias herelic='heroku addons:open newrelic'
alias helog='heroku logs'
alias helgrep='heroku logs | grep '

# !=== NODE ===
alias jcfe='jasmine-node --coffee'

# !=== CHEF ===
alias kfb='knife bootstrap'
alias kfc='knife cookbook'
alias kfcsi='knife cookbook site install'

# !=== RBENV ===
alias rbh='rbenv rehash'
