if [[ $platform == 'linux' ]]; then
	alias ls='ls -F --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias senz='sensors'

	alias myxstart='sudo service mysql start'
	alias mystop='sudo service mysql stop'
	alias myrestart='sudo service mysql restart'

	# !=== Ubuntu specific ===
	alias aptup='sudo apt-get update'
	alias aptug='sudo apt-get upgrade'
	alias aptuu='sudo apt-get update && sudo apt-get upgrade'
	alias aptrepo='sudo add-apt-repository '
	alias aptcs='apt-cache search '

elif [[ $platform == 'darwin' ]]; then
	alias ls='ls -CF'
	alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
	alias updatedb='sudo /usr/libexec/locate.updatedb'
	alias bash-refresh='. ~/.bash_profile'
fi

alias cbag='cat ~/.bash_aliases | grep '

# linux, put in /etc/bash.bashrc
alias clr='clear'
alias ..='cd ..'
alias ...='cd ../../'
alias ..3='cd ../../../'

alias la='ls -a'
alias ll='ls -al'
alias l='ls'
# /etc/bash.bashrc

alias wol='wakeonlan'

# === Script ===
alias rby='ruby'
alias py='python'
alias elx='elixir'

# === GIT ===
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log'
alias gl1='git log --oneline --decorate'
alias gst='git status -sb'
alias gstt='git status'
alias ga='git add --ignore-removal'
alias grh='git reset HEAD'
alias gcmm='git commit -m'
alias gph='git push'
alias gpl='git pull'
alias gb='git branch'
alias gbr='git branch --remote'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcu='git checkout uat'
alias gcp='git checkout production'
alias gto='git checkout -' # switch between two current branches

# === RAILS ===
alias rc='bundle exec rails console'
alias rcb='bundle exec rails console --sandbox'
alias rct='RAILS_ENV=test bundle exec rails console'
alias rs='bundle exec rails server -b 0.0.0.0'

alias bx='bundle exec'
alias bxan='bundle exec annotate'
alias bxr='bundle exec rspec'
alias bxc='bundle exec rubocop'

# === RAKE ===
alias rake-reset-devdb='RACK_ENV=development RAILS_ENV=development bundle exec rake db:drop db:create db:migrate'
alias rake-reset-testdb='RACK_ENV=test RAILS_ENV=test bundle exec rake db:drop db:create db:migrate'
alias rake-prepare-testdb='RACK_ENV=test RAILS_ENV=test bundle exec rake db:test:prepare'
alias rrgrep='rake routes | grep '

# === React Native ===
alias rem='adb shell input keyevent 82'
alias ran='react-native run-android'
alias rio='react-native run-android'
alias xrev='adb reverse tcp:8081 tcp:8081'
alias xlog='adb logcat *:S ReactNative:V ReactNativeJS:V'

# === adb ===
alias atx='adb shell input text'

# === Android ===
alias 5x_5='emulator -avd Nexus_5X_5 -gpu on -no-boot-anim'
alias 5x_51='emulator -avd Nexus_5X -gpu on -no-boot-anim'
alias 5x_6='emulator -avd Nexus_5X_6 -gpu on -no-boot-anim'

alias opensslrand='openssl rand -base64'

# === TensorFlow ===
alias tfactivate='source $HOME/tensorflow/bin/activate'
