if [[ $platform == 'linux' ]]; then
	alias ls='ls -F --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias senz='sensors'

	alias myxstart='sudo service mysql start'
	alias mystop='sudo service mysql stop'
	alias myrestart='sudo service mysql restart'

	# !=== Ubuntu specific ===
	alias aptup='sudo apt-get update'
	alias aptug='sudo apt-get upgrade'
	alias aptuu='sudo apt-get update && sudo apt-get upgrade'
	alias aptrepo='sudo add-apt-repository '
	alias aptcs='apt-cache search '

elif [[ $platform == 'darwin' ]]; then
	alias ls='ls -CF'
	alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
	alias updatedb='sudo /usr/libexec/locate.updatedb'

	alias lload='launchctl load'
	alias lunload='launchctl unload'
	alias sulload='sudo launchctl load'
	alias sulunload='sudo launchctl unload'

	alias myload='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
	alias myunload='launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
	alias nginxload='sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist'
	alias nginxunload='sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist'
fi

alias cbag='cat ~/.bash_aliases | grep '
alias bashrefresh='. ~/.bash_profile'

# linux, put in /etc/bash.bashrc
alias clr='clear'
alias ..='cd ..'
alias ...='cd ../../'
alias ..3='cd ../../../'

alias la='ls -a'
alias ll='ls -al'
alias l='ls'
# /etc/bash.bashrc

# === Script ===
alias rby='ruby'
alias cfe='coffee'
alias py='python'

# === GIT ===
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log'
alias gl1='git log --oneline --decorate'
alias gf='git fetch'
alias gst='git status -sb'
alias gstl='git status'
alias ga='git add --ignore-removal'
alias gaa='git add --all'
alias grh='git reset HEAD'
alias gc='git commit'
alias gcmm='git commit -m'
alias gca='git commit -a'
alias gph='git push'
alias gpl='git pull'
alias gb='git branch'
alias gbr='git branch --remote'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcp='git checkout production'
alias gto='git checkout -' # switch between two current branches

# === GEMS ===
alias ccb='cucumber'
alias rsp='rspec'
alias shotgun47='shotgun --port=4567'

# === RAILS ===
alias rn='rails new'
alias rcb='rails console --sandbox'
alias rct='RAILS_ENV=test rails console'
alias rc='rails console'
alias rg='rails generate'
alias rd='rails destroy'

alias rs='rails server -b 0.0.0.0'
alias rs31='rails server -b 0.0.0.0 --port=3001'
alias rs32='rails server -b 0.0.0.0 --port=3002'
alias rs33='rails server -b 0.0.0.0 --port=3003'
alias rs34='rails server -b 0.0.0.0 --port=3004'
alias rs35='rails server -b 0.0.0.0 --port=3005'

alias r2s='script/server'
alias r2c='script/console'

alias bx='bundle exec'
alias bxan='bundle exec annotate'
alias bxr='bundle exec rspec'
alias bxc='bundle exec cucumber'

# === RAKE ===
alias rails-reset-testdb='bundle exec rake db:drop RAILS_ENV=test; bundle exec rake db:create RAILS_ENV=test; bundle exec rake db:migrate RAILS_ENV=test'
alias rrt='rake routes'
alias rrgrep='rake routes | grep '
alias rdstt='rake db:migrate:status'

alias bxdl='bundle exec rake db:schema:load; bundle exec rake db:schema:load RAILS_ENV=test'
alias bxdm='bundle exec rake db:migrate; bundle exec rake db:migrate RAILS_ENV=test'
alias bxdre='bundle exec rake db:migrate:redo; bundle exec rake db:migrate:redo RAILS_ENV=test'
alias bxddr='bundle exec rake db:drop; bundle exec rake db:drop RAILS_ENV=test'
alias bxdrb='bundle exec rake db:rollback'

# === EMBER ===
alias eg='ember generate'

# === GRUNT ===
alias grtw='grunt watch'

# === RBENV ===
alias rbh='rbenv rehash'

# === React Native ===
alias rem='adb shell input keyevent 82'
alias ran='react-native run-android'
alias rio='react-native run-android'
alias xrev='adb reverse tcp:8081 tcp:8081'
alias xlog='adb logcat *:S ReactNative:V ReactNativeJS:V'

# === adb ===
alias atx='adb shell input text'

# === Android ===
alias 5x_5='emulator -avd Nexus_5X_5 -gpu on -no-boot-anim'
alias 5x_51='emulator -avd Nexus_5X -gpu on -no-boot-anim'
alias 5x_6='emulator -avd Nexus_5X_6 -gpu on -no-boot-anim'

alias opensslrand='openssl rand -base64'
alias psg='ps auxw | grep'
